Crypto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coins.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import SignUP

urlpatterns = [
    path('signup/', SignUP.as_view(), name='signup')
]

coins/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CoinsViews.as_view(), name='home'),
    path('<slug:slug>/', views.CoinDetail.as_view(), name='coin_detail'),
    path('reviews/<int:pk>', views.AddReview.as_view(), name='add_review')
]

accounts/models.py
from django.db import models

# Create your models here.

coins/models.py
from django.db import models
from django.urls import reverse

class Algo(models.Model):
    '''Алгоритмы'''
    title = models.CharField('Название алгоритма', max_length=50)
    description = models.TextField('Описание алгоритма', blank=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Алгоритм'
        verbose_name_plural = 'Алгоритмы'

class Method(models.Model):
    '''Метод добычи'''
    title = models.CharField('Название метода', max_length=20)
    description = models.TextField('Описание метода', blank=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Доказательство работы/доли'
        verbose_name_plural = 'Доказательство работы/доли'

class Currency (models.Model):
    '''Биржи'''
    title = models.CharField('Название биржи', max_length=50)
    description = models.TextField('Описание биржи', blank=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Биржа'
        verbose_name_plural = 'Биржи'

class Coin(models.Model):
    '''Информация о монете'''
    title = models.CharField('Название монеты', max_length=100)
    imag = models.ImageField('Картинка', upload_to='image/&Y')
    description = models.TextField('Описание', blank=True)
    date_publ = models.DateField('Дата выхода')
    method = models.ManyToManyField(Method, blank=True, verbose_name='Доказательство работы/доли')
    algo = models.ManyToManyField(Algo, blank=True, verbose_name='Алгоритмы')
    currency = models.ManyToManyField(Currency, blank=True, verbose_name='Биржи')
    url = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return f'{self.title}, {self.date_publ}'

    def get_absolute_url(self):
        return reverse('coin_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Монета'
        verbose_name_plural = 'Монеты'

class Reviews(models.Model):
    '''Отзывы'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text = models.TextField('Текст отзыва', max_length=2000)
    coin = models.ForeignKey(Coin, verbose_name='Монета', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.coin}'

    class Meta:
        verbose_name = 'Монета'
        verbose_name_plural = 'Монеты'

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUP(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

coins/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Coin
from .form import ReviewForm

class CoinsViews(View):
    '''Список монет'''
    def get(self, request):
        coins = Coin.objects.all()
        return render(request, 'coins/coin.html', {'coin_list': coins})

class CoinDetail(View):
    '''Представление одной монеты'''
    def get(self, request, slug):
        coin = Coin.objects.get(url=slug)
        return render(request, 'coins/coin_detail.html', {'coin': coin})

class AddReview(View):
    '''Добавление отзыва'''
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        coin = Coin.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.coin = coin
            form.save()
        return redirect(coin.get_absolute_url())

templates/coins/coin.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>Прогноз курса криптовалют</title>
</head>
<body>

    <div id="root">
        <div>
            <ul class="menu">
                <li><a href="/">Главная</a></li>
                <li><a href="/">Монеты</a></li>
                <li><a href="/">Торговые сигналы</a></li>
            </ul>
        </div>
            <div class="auth">
                <a href="/">Главная</a>
                {% if user.is_authenticated %}
                <p>Привет, {{ user.username }}, вы авторизованы на сайте!</p>
                <a href="{% url 'logout' %}">Выход</a>
                {% else %}
                <a href="{% url 'signup' %}">Регистрация</a>
                <a href="{% url 'login' %}">Авторизация</a>
                {% endif %}
            </div>
        
    <div class="body">
        {% for coin in coin_list %}
            <h2>Монета: <a href="/{{ coin.url }}/">  {{ coin.title }} </a></h2>
                <img src="{{ coin.imag.url }}" width="150px" height="">
                Описание: {{ coin.description }}
                {% for algo in coin.algo.all %}
                Алгоритм: {{ algo.title }}
                {% endfor %}
                {% for method in coin.method.all %}
                Метод добычи: {{ method.title }}
                {% endfor %}
        
        {% endfor %}
    </div>
</body>
</html>

templates/coins/coin_detail.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <a href="/">Главная</a>
        {% if user.is_authenticated %}
        <p>Привет, {{ user.username }}, вы авторизованы на сайте!</p>
        <a href="{% url 'logout' %}">Выход</a>
        {% else %}
        <a href="{% url 'signup' %}">Регистрация</a>
        <a href="{% url 'login' %}">Авторизация</a>
        {% endif %}
    </div>

    <h2>Монета: {{ coin.title }}</h2>
        <p>Описание: {{ coin.description }}</p>
        <p>{% for algo in coin.algo.all %}
        Алгоритм: {{ algo.title }}
        {% endfor %}
        </p>
        <p>{% for method in coin.method.all %}
        Метод добычи: {{ method.title }}
        {% endfor %}
        </p>
        <p><img src="{{ coin.imag.url }}" width="150px" height=""</p>

    <div>
        {% for review in coin.reviews_set.all %}
            <div>
                <h5>{{ review.name }}</h5>
                <p>{{ review.text }}</p>
            </div>
        {% endfor %}
    </div>

    <div>
        <span>Оставить отзыв:</span>
        <form action = "{% url 'add_review' coin.id %}" method="post">
            {% csrf_token %}
            <div>
                <label>Ваш отзыв</label>
                <textarea name="text"></textarea>
            </div>
            <div>
                <label>Ваше имя</label>
                <input type="text" name="name">
            </div>
            <div>
                <label>Ваш email</label>
                <input type="email" name="email">
            </div>
            <div>
                <input type="submit">
            </div>
        </form>
    </div>
</body>
</html>

templates/coins/index.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>{{ coin.title }}</title>
</head>
<body>
    <div id="root">
    <div class="menu">
        <a href="/">Главная</a>
        {% if user.is_authenticated %}
        <p>Привет, {{ user.username }}, вы авторизованы на сайте!</p>
        <a href="{% url 'logout' %}">Выход</a>
        {% else %}
        <a href="{% url 'signup' %}">Регистрация</a>
        <a href="{% url 'login' %}">Авторизация</a>
        {% endif %}
    </div>

    <h2>Монета: {{ coin.title }}</h2>
        <p><img src="{{ coin.imag.url }}" width="150px" height=""></p>
        <p>Описание: {{ coin.description }}</p>
        <p>{% for algo in coin.algo.all %}
        Алгоритм: {{ algo.title }}
        {% endfor %}
        </p>
        <p>{% for method in coin.method.all %}
        Метод добычи: {{ method.title }}
        {% endfor %}
        </p>
        
    <div>
        {% for review in coin.reviews_set.all %}
            <div>
                <h5>{{ review.name }}</h5>
                <p>{{ review.text }}</p>
            </div>
        {% endfor %}
    </div>
    
    <div>
        <span>Оставить отзыв:</span>
        <form action = "{% url 'add_review' coin.id %}" method="post">
            {% csrf_token %}
            <div>
                <label>Ваш отзыв</label>
                <textarea name="text"></textarea>
            </div>
            <div>
                <label>Ваше имя</label>
                <input type="text" name="name">
            </div>
            <div>
                <label>Ваш email</label>
                <input type="email" name="email">
            </div>
            <div>
                <input type="submit">
            </div>
        </form>
    </div>
</div>
</body>
</html>